# -*- eval: (variable-pitch-mode 0); -*-

#+TITLE: Description:

* Guix System & various application configs

This repo contains my GNU Guix System configuration, along with various application configs. 

GNU Guix System is a Linux distribution that provides a declarative operating system configuration, just like NixOS. In this repo, I have configs that define everything ranging from system and user-level services, packages separated into manifests, filesystem layout, and much more.

The application configs in this repo include those for several Wayland compositors, several X window managers, sereval old emacs configs (newest one is hosted here: <link>), too many POSIX shellscripts, and etc.

* Info and navigation to parts of repo:

WIP

* Notes to self:

** Post-installation

make sure EVERYTHING is reproducible, in case this happens again

make snapshotting and store integrity-checking system, daily, or at least very frequently

.guix-profile is never updated, only .guix-extra-profiles. edit the script to ensure that the default profile is being upgraded as well!

** TODO Now

- [X] Restore firefox bookmarks and add new ones from other laptop
- [X] save new nyanko.scm
  - [X] FIX GIT GPG ACCESS
- [X] create modules for stow dotfiles
- [X] create script for volume-up key, check if current volume is <= 100, if yes, allow inc script arg amount, check val again, if over 100, set back to 100
- [X] faster grub decrypt:
  - [X] make key slot 0 the new primary one, with the preferred password, with iterations 1000.
  - [X] restart to check.
  - [X] make key slot 1 the old pass, with iterations 1000.
  - [X] restart to check.
  - [X] delete slot 2
- [X] move dotfiles to nya guix repo
- [ ] prepare org mode for new semester (statistics)
- [ ] change sandbar to where current pink is grey and pink is text, inversion.
- [ ] patch TamzenForPowerline font using special arguments... make sure not to overwrite existing... experiment!!! also add patched to github repo.
- [ ] update fontconfig to include all profiles' share dir
- [ ] bar
  - [ ] use darker color title-bg and white title-fg, better.
  - [ ] wifi indicator on statusbar
  - [ ] yambar instead?
- [ ] write guix packages
  - [ ] rust flow package
  - [ ] python bemenu script, using nix upstream definition.
- [ ] read other's river configs and hack more the shit out of!!!
- [ ] new emacs features
  - [ ] rss - phundrak, 
- [ ] auto guix upkeep script (use fzf!!!!!):
  - [ ] verify store integrity
  - [ ] btrfs snapshotting with snapper
  - [ ] make sure guix default profile is being updated, not just the extra profiles (rewrite update script?).
- [ ] keyfile encryption boot skip
  - [ ] Create persist subvol from chroot, reconfigure, if work, try adding keyfile in /persist/key-file.cpio, hope it works.
  - [ ] test if zstd format works, only in root subvol (also noatime? what does that even do?)
- [ ] vpn shuffle through mullvad vpns, set all to don't autoconnect except one random, will update next wake from sleep

Long future:
- improve and neaten arkenfox overrides into neater form
  - arkenfox-updater, keep expected firefox version in file, compare to output of "firefox --version" | regex !
- (l)figure out a way to fix stumpwm root user (get river all set up beforehand)
- personal website with photos, org mode?
- sign all commits in emacs repo?
- create music dir (bandcamp lolecore), have all local music on there, rsync to phone easily (in the future, homelab and stream?).

