hack: &hack Hack Nerd Font:pixelsize=13

awesome: &awesome Font Awesome 6 Free:style=solid:pixelsize=14
awesome_brands: &awesome_brands Font Awesome 6 Brands:pixelsize=16

bg_default: &bg_default {stack: [{background: {color: 81A1C1ff}}, {underline: {size: 4, color: D8DEE9ff}}]}

# BAR
bar:

  ## Spacing
  
  height: 26
  # location: top
  location: bottom
  spacing: 5
  margin: 7
  
  # height: 20
  # location: top
  # spacing: 2
  # margin: 0

  ## Colors

  foreground: ffffffff
  background: 111111cc

  # foreground: eeeeeeff
  # background: 2E3440dd

  ## Border around bar

  border:
    width: 1
    color: 999999cc
    margin: 5
    top-margin: 0

  ## Other

  font: JuliaMono:pixelsize=10
  layer: bottom

  ## Left-side
  
  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 13
              default: {string: {text: , font: *hack}}
              conditions:
                id == 1: {string: {text: ﳐ, font: *hack}}
                id == 2: {string: {text: , font: *hack}}
                id == 3: {string: {text: , font: *hack}}
                id == 4: {string: {text: , font: *hack}}
                id == 5: {string: {text: , font: *hack}}
                id == 10: {string: {text: "scratchpad", font: *hack}}
                id == 11: {string: {text: "work", font: *hack}}
                
        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: D08770ff}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 3, color: ea6962ff}}
